name: お問い合わせ
description: MERINPOに関するご質問・不具合報告・ご要望はこちらから
title: "[Contact] "
labels: ["contact"]
body:
  - type: input
    id: name
    attributes:
      label: お名前（任意）
      placeholder: 例）山田太郎
    validations:
      required: false

  - type: input
    id: email
    attributes:
      label: メールアドレス（任意・返信希望時のみ）
      placeholder: 例）example@example.com
    validations:
      required: false

  - type: textarea
    id: content
    attributes:
      label: お問い合わせ内容
      description: 不具合内容・要望・その他ご連絡事項をご記入ください
      placeholder: できるだけ詳しくご記載ください
    validations:
      required: true
